### ISSUE TITLE
HTML parse error

### ISSUE THREAD

**Issue by BigErn77** [DrKylstein/retro-proxy#7]
at new HTMLParser (/Volumes/WD2TB2/misc/dev/retro-proxy/node_modules/html-minifier/src/htmlparser.js:244:13)
    at minify (/Volumes/WD2TB2/misc/dev/retro-proxy/node_modules/html-minifier/src/htmlminifier.js:980:3)
    at exports.minify (/Volumes/WD2TB2/misc/dev/retro-proxy/node_modules/html-minifier/src/htmlminifier.js:1341:16)
    at /Volumes/WD2TB2/misc/dev/retro-proxy/index.js:152:11

I occasionally get HTMLparser errors. Here is a URL with which I could consistently reproduce it:

http://oldavista.com/faq

**Comment by DrKylstein** [comment]
Handled in e5c34957b0bc18c472ee8da01004f6f23770e6bb

I can't fix the underlying issue, which is some HTML that is invalid according to modern standards. However, the way the error was handled wasn't very good. I've improved that. 

oldavista.com is a retro site though, and retro sites should be added to allowed.txt. I've added it to the example list in the repo.
